### ISSUE TITLE
Suggestion:adding a another way to input the loan withdraw's input,such as chat instead of anvil

### ISSUE THREAD

**Issue by 1640946640** [AshleyThew/Bank#6]
Monster_ issued server command: /菜单
[23:48:52] [Server thread/INFO]: Monster_ issued server command: /菜单
[23:48:55] [Server thread/INFO]: [Core] Attempting to load default AnvilUtil
[23:48:55] [Server thread/INFO]: [Core] Attempting to load 1.16 AnvilUtil
[23:48:55] [Server thread/INFO]: [Core] Loaded 1.16, enjoy :)
[23:48:55] [Server thread/WARN]: java.lang.NullPointerException
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.impl._16AnvilUtil.open(_16AnvilUtil.java:148)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.AnvilUtil.open(AnvilUtil.java:49)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.AnvilInventory.open(AnvilInventory.java:61)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:99)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:84)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.loan.BankLoanTakeOutInventory.setAmount(BankLoanTakeOutInventory.java:130)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$setItem$6(BankInventoryHandler.java:35)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157)
[23:48:55] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:243)
[23:48:55] [Server thread/WARN]:        at catserver.server.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source)
[23:48:55] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67)
[23:48:55] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:48:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[23:48:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[23:48:55] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2215)
[23:48:55] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[23:48:55] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[23:48:55] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:48:55] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:48:55] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:48:55] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:48:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
[23:48:55] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[23:48:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
[23:48:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
[23:48:55] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:750)
[23:48:58] [Server thread/WARN]: java.lang.NullPointerException
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.impl._16AnvilUtil.open(_16AnvilUtil.java:148)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.AnvilUtil.open(AnvilUtil.java:49)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.AnvilInventory.open(AnvilInventory.java:61)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:99)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:84)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.loan.BankLoanTakeOutInventory.setAmount(BankLoanTakeOutInventory.java:130)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$setItem$6(BankInventoryHandler.java:35)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157)
[23:48:58] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:243)
[23:48:58] [Server thread/WARN]:        at catserver.server.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source)
[23:48:58] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67)
[23:48:58] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:48:58] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[23:48:58] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[23:48:58] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2215)
[23:48:58] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[23:48:58] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[23:48:58] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:48:58] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:48:58] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:48:58] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:48:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
[23:48:58] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[23:48:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
[23:48:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
[23:48:58] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:750)
[23:49:03] [Server thread/WARN]: java.lang.NullPointerException
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.impl._16AnvilUtil.open(_16AnvilUtil.java:148)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.AnvilUtil.open(AnvilUtil.java:49)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.AnvilInventory.open(AnvilInventory.java:61)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:99)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:84)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.loan.BankLoanTakeOutInventory.setAmount(BankLoanTakeOutInventory.java:130)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$setItem$6(BankInventoryHandler.java:35)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157)
[23:49:03] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:243)
[23:49:03] [Server thread/WARN]:        at catserver.server.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source)
[23:49:03] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67)
[23:49:03] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:49:03] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[23:49:03] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[23:49:03] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2215)
[23:49:03] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[23:49:03] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[23:49:03] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:49:03] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:49:03] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:49:03] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:49:03] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
[23:49:03] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[23:49:03] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
[23:49:03] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
[23:49:03] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:750)`

**Comment by 1640946640** [comment]
My server version: 1.12.2,but accroding to the logs show that it loads the 1.16，Wish u can fix it as soon as possible

**Comment by 1640946640** [comment]
U can try the another way to makes sure my function of loan,which can be used normally.For instance,When I couldn't use the anvil inventory,the plugin will automatically open this interface in other ways, such as chat or other input interfaces

**Comment by 1640946640** [comment]
It is too weird！Sometimes it works normally,sometimes it doesn't work.When this plugin works normally,another plugin report error!
`[Minecraft]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_371]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1105) [CraftEventFactory.class:git-CatServer-1.12.2-5a600445]
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:377) [afs.class:?]
	at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:489) [afs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:2873) [pa.class:?]
	at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) [lh.class:?]
	at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) [lh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_371]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_371]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]
[00:21:37] [Craft Scheduler Thread - 861/INFO] []: [Bank] Running LoansDeadlineManager
[00:21:37] [Craft Scheduler Thread - 861/INFO] []: [Bank] Handling Loans Deadlines
[00:21:52] [Server thread/ERROR] [Minecraft]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_371]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1105) [CraftEventFactory.class:git-CatServer-1.12.2-5a600445]
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:377) [afs.class:?]
	at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:489) [afs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:2873) [pa.class:?]
	at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) [lh.class:?]
	at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) [lh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_371]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_371]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]`
