### ISSUE TITLE
Could not pass event InventoryClickEvent to Core v0.6.4

### ISSUE THREAD

**Issue by Lice2** [AshleyThew/Bank#9]
Server: paper-1.21.1-65.jar
Java21

Bank items don't work and this error occurs.

`[19:55:09 ERROR]: Could not pass event InventoryClickEvent to Core v0.6.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because the return value of "me.dablakbandit.bank.player.info.item.BankItem.getItemStack()" is null
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.getItemStack(BankItemsInventory.java:354) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.lambda$addItems$2(BankItemsInventory.java:146) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.lambda$setItem$0(InventoryHandler.java:47) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.set(InventoryHandler.java:139) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.set(BankInventoryHandler.java:125) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.set(BankItemsInventory.java:370) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.open(InventoryHandler.java:122) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.open(BankInventoryHandler.java:120) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.open(InventoryHandler.java:128) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:99) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:84) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoriesManager.open(BankInventoriesManager.java:50) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventories.accept(BankInventories.java:73) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventories.accept(BankInventories.java:26) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$consumeSound$30(BankInventoryHandler.java:87) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.lambda$setItem$7(InventoryHandler.java:98) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:243) ~[core-latest.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3216) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by AshleyThew** [comment]
Have you updated as it says in the update notes?
https://www.spigotmc.org/resources/bank-1-21-sale-20-off.3556/update?update=556276

**Comment by Lice2** [comment]
I did 4.8.0 under 1.20.4.
It also converted.
Now under 1.20.1 everything works except for the items.
So you can deposit and withdraw money. And the experience points work perfectly too.
The error only comes up when I want to access the items.

When I start the bank plugin I also get errors from the core.

`[03:00:42] [Server thread/INFO]: [Bank] Loading server plugin Bank v4.8.1-RELEASE
[03:00:42] [Server thread/INFO]: [Core] Checking update for Bank v4.8.1-RELEASE
[03:00:43] [Server thread/INFO]: [Core] Attempting to load default ItemUtils
[03:00:44] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "this.nmscopy" is null
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.itemutils.DefaultItemUtils.getNMSCopy(DefaultItemUtils.java:55)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.itemutils.DefaultItemUtils.convertItemStackToJSON(DefaultItemUtils.java:1279)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.ItemUtils.load(ItemUtils.java:29)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.ItemUtils.<clinit>(ItemUtils.java:15)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.json.serializer.ItemStackSerializer.deserialize(ItemStackSerializer.java:43)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.json.JSONDataFactory$1.read(JSONDataFactory.java:31)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:1227)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:1137)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:1047)
[03:00:44] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:982)
[03:00:44] [Server thread/WARN]: 	at core-latest.jar//me.dablakbandit.core.utils.json.JSONParser.fromJSON(JSONParser.java:57)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.implementations.blacklist.ItemBlacklistImplementation.lambda$new$0(ItemBlacklistImplementation.java:28)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.implementations.blacklist.ItemBlacklistImplementation.<init>(ItemBlacklistImplementation.java:28)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.implementations.blacklist.ItemBlacklistImplementation.<clinit>(ItemBlacklistImplementation.java:17)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.inventory.admin.blacklist.BankBlacklistPlayerHandler.<init>(BankBlacklistPlayerHandler.java:17)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.inventory.PlayerInventoryHandlers.<clinit>(PlayerInventoryHandlers.java:17)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.inventory.BankInventories.<clinit>(BankInventories.java:28)
[03:00:44] [Server thread/WARN]: 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[03:00:44] [Server thread/WARN]: 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
[03:00:44] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
[03:00:44] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
[03:00:44] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159)
[03:00:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
[03:00:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[03:00:44] [Server thread/WARN]: 	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:4014)
[03:00:44] [Server thread/WARN]: 	at java.base/java.lang.System$2.getEnumConstantsShared(System.java:2367)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.EnumMap.getKeyUniverse(EnumMap.java:750)
[03:00:44] [Server thread/WARN]: 	at java.base/java.util.EnumMap.<init>(EnumMap.java:138)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.inventory.BankInventoriesManager.<init>(BankInventoriesManager.java:26)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.inventory.BankInventoriesManager.<clinit>(BankInventoriesManager.java:18)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.BankCoreHandler.loadOther(BankCoreHandler.java:222)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.BankCoreHandler.load(BankCoreHandler.java:94)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.BankCoreHandler.onLoad(BankCoreHandler.java:70)
[03:00:44] [Server thread/WARN]: 	at bank-plugin-latest-all.jar//me.dablakbandit.bank.BankPlugin.onLoad(BankPlugin.java:42)
[03:00:44] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[03:00:44] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[03:00:44] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[03:00:44] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[03:00:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
[03:00:44] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
[03:00:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[03:00:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[03:00:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by AshleyThew** [comment]
Is core up to date?

**Comment by Lice2** [comment]
name: Core
author: Dablakbandit
main: me.dablakbandit.core.CorePlugin
version: 0.6.4
loadbefore: [ViaVersion]
load: STARTUP
api-version: 1.13

**Comment by AshleyThew** [comment]
Try resetting the blacklist in the bank config

**Comment by Lice2** [comment]
my config.yml from the survival Server. 

    Trashcan:
      # Enable the trashcan in the item gui
      Enabled: true
      Blacklist:
        # Enable the trashcan blacklist, requires the normal item blacklist to also be enabled
        Enabled: false
        # Blacklist mode (blacklist/whitelist)
        Mode: BLACKLIST

    Blacklist:
      # Enable item blacklist
      Enabled: false
      # Blacklist mode (blacklist/whitelist)
      Mode: BLACKLIST

**Comment by AshleyThew** [comment]
conf/itemblacklist.yml

**Comment by Lice2** [comment]
OK, now there are no more errors from the core.
I just have to test in-game whether it works.
Thanks for that!

**Comment by Lice2** [comment]
No, unfortunately it still doesn't work.
This error appears in the console.

`[14:41:53 ERROR]: Could not pass event InventoryClickEvent to Core v0.6.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because the return value of "me.dablakbandit.bank.player.info.item.BankItem.getItemStack()" is null
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.getItemStack(BankItemsInventory.java:354) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.lambda$addItems$2(BankItemsInventory.java:146) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.lambda$setItem$0(InventoryHandler.java:47) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.set(InventoryHandler.java:139) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.set(BankInventoryHandler.java:125) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.item.BankItemsInventory.set(BankItemsInventory.java:370) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.open(InventoryHandler.java:122) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.open(BankInventoryHandler.java:120) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.open(InventoryHandler.java:128) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:99) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:84) ~[core-latest.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoriesManager.open(BankInventoriesManager.java:50) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventories.accept(BankInventories.java:73) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventories.accept(BankInventories.java:26) ~[bank-plugin-latest-all.jar:?]
        at bank-plugin-latest-all.jar/me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$consumeSound$30(BankInventoryHandler.java:87) ~[bank-plugin-latest-all.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.lambda$setItem$7(InventoryHandler.java:98) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157) ~[core-latest.jar:?]
        at core-latest.jar/me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:243) ~[core-latest.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3216) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by AshleyThew** [comment]
Looks like what might happen if you updated the plugin before migrating the database, or an item has strangely become null. Maybe a custom item that no longer exists? No really sure as I don't have your bank player data.
I can remove null items on load to potentially fix this issue?
Assuming you are on premium so getting an update would take a few days with this change

**Comment by Lice2** [comment]
Yes, I suspect that too.
I used the Nova plugin on another server and the Bank plugin to transfer items from the Survival Server to the Mod Server.
So I think that the zero items are there now.
And yes, I bought the Bank plugin (Premium)
.

**Comment by AshleyThew** [comment]
Can you download this version: https://github.com/AshleyThew/Bank/blob/main/output/bank-plugin-lite-latest-all.jar
It is lite version but will work for this use case

1. Stop server & Backup data
2. Swap premium jar for lite version above
3. In upgrade.yml set UPGRADE_DATABASE_CLEANUP to true
4. Start server it should print cleanup progress
5. Stop server and swap back to premium

**Comment by Lice2** [comment]
in my upgrade.yml is this.

Upgrade:
  # No upgrade needed at this time
  Confirm: false
  # DO NOT TOUCH, THIS WILL TRIGGER AN UPGRADE
  Version: 480
  Conversion:
    # SET THIS ONLY TO TRUE IF UPGRADING FROM BEFORE 4.1.0
    # THIS WILL TRIGGER A CONVERSION, WHICH MAY TAKE SOME TIME
    # MAKE SURE TO BACKUP OLD BANK DATA
    Old: false
    # IF USING MYSQL ON THE OLD PLUGIN AND WISH TO KEEP USING MYSQL SET THIS TO TRUE
    Mysql: false
